---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/damiansol/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .ssh
  - .bash_aliases
  - .bash_profile
  - .bashrc
  - .gitconfig
  - .nanorc
  - .profile
  - .screenrc
  - .taskrc
  - .tmux.conf
  - .zshrc

homebrew_installed_packages:
  - bash
  - bash-completion@2
  - bash-git-prompt
  - bat
  - cgoban
  - dust
  - exa
  - fd
  - fzf
  - gh
  - git
  - gpg
  - htop
  - hub
  - ipython
  - jupyterlab
  - k9s
  - kind
  - nano
  - numpy
  - pyenv
  - pipenv
  - ripgrep
  - rsync
  - tldr
  - watch
  - wget
  - wtf

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/autoupdate
  - homebrew/cask-drivers

homebrew_cask_appdir: /Applications
homebrew_cask_apps:

# Apps to add:
# - Arturia downloader thingy // only for music computer
  - 1password
  - a-better-finder-rename
  # - ableton-live-suite // only for music computer
  - adobe-creative-cloud
  - arc
  - asana
  - brave-browser
  - discord
  - dropbox
  - evernote
  - firefox
  - google-drive
  # - ilok-license-manager // only for music computer
  - iterm2
  - microsoft-powerpoint
  - microsoft-word
  - microsoft-excel
  # - native-access // only for music computer
  - nativedisplaybrightness
  - rectangle
  - signal
  - slack
  # - soundtoys // only for music computer 
  - spotify
  - sublime-text
  - textexpander
  - teamviewer
  - visual-studio-code
  - vlc
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 682658836, name: "GarageBand" }
  - { id: 409035833, name: "iReal Pro" }
  - { id: 634148309, name: "Logic Pro" }
  - { id: 585829637, name: "Todoist" }
  - { id: 405537804, name: "Sound Studio" }
  - { id: 506189836, name: "Harvest" }
  # - { id: 1339418001, name: "Minimoog Model D Synthesizer" } // only for music computer
  - { id: 405399194, name: "Kindle" }
  - { id: 1033342465, name: "Just Press Record" }

mas_email: "manwreck@icloud.com"
mas_password: "[saRDWNWUqf2ks>Cw4WjJtUxuVVWG]E"

osx_script: "~/.osx --no-restart"

extra_args: "--user"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:  
  # - name: pipsi
  # - name: pygments
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

